package org.curator.common.model;

public enum MetricName {
    WORD_COUNT,
    SENTENCE_COUNT,
    AMDAHL, FLESCH, SMOG,
    UNIQUE_USER_COUNT,
    RECURRING_FACTOR,
    MENTIONED_USER_COUNT,
    ARTICLE_FRESHNESS,
    VIEW_COUNT,
    COMMENT_FRESHNESS,
    TWEET_COUNT,
    OUTGOING_LINK_COUNT,
    TYPE_TOKEN_RATIO
}
